// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.5.3
// source: broker.proto

package servicepb

import (
	context "context"
	proto "go.unistack.org/micro-broker-service/v3/proto"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	BrokerName = "Broker"

	BrokerEndpoints = []api.Endpoint{}
)

func NewBrokerEndpoints() []api.Endpoint {
	return BrokerEndpoints
}

type BrokerClient interface {
	Publish(ctx context.Context, req *proto.PublishRequest, opts ...client.CallOption) (*proto.Empty, error)
	Subscribe(ctx context.Context, req *proto.SubscribeRequest, opts ...client.CallOption) (Broker_SubscribeClient, error)
}

type Broker_SubscribeClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Recv() (*proto.Message, error)
}

type BrokerServer interface {
	Publish(ctx context.Context, req *proto.PublishRequest, rsp *proto.Empty) error
	Subscribe(ctx context.Context, req *proto.SubscribeRequest, stream Broker_SubscribeStream) error
}

type Broker_SubscribeStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Send(msg *proto.Message) error
}
